name: "Mark stale issues"

on:
  schedule:
    - cron: "0 0 * * *"  # 每天的 UTC 时间 00:00 运行
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Mark stale issues
        uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            这个 issue 因为最近没有活动而被自动标记为过期。如果没有进一步的活动，它将被关闭。感谢您的贡献。
            This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
            この issue は最近活動がなかったため、自動的に期限切れとしてマークされました。さらなる活動がない場合は、閉鎖されます。ご協力ありがとうございます。
          days-before-stale: 7
          days-before-close: 3
          stale-issue-label: '过期'
          exempt-issue-labels: '安全,pinned,BUG,需要补充,增强'
          operations-per-run: 30
          remove-stale-when-updated: true
          debug-only: false
